
 create table projects (
   id int8 generated by default as identity,
   description varchar(255),
   name varchar(255),
   primary key (id)
);

 create table records (
   id int8 generated by default as identity,
   description varchar(2048) not null,
   name varchar(255),
   end_time timestamp,
   start_time timestamp,
   project_id int8 not null,
   user_id int8 not null,
   primary key (id)
);

 create table user_roles (
   user_id int8 not null,
   role varchar(255)
);

 create table users (
   id int8 generated by default as identity,
   password varchar(255), username varchar(255),
   primary key (id)
);

 alter table if exists users
  add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);

 alter table if exists records
  add constraint FKe0lct7m7dyfir8ogwhslsh75
  foreign key (project_id) references projects;

 alter table if exists records
  add constraint FK6p95uajgka0j0dc9vlbjw1sf1
  foreign key (user_id) references users;

 alter table if exists user_roles
  add constraint FKhfh9dx7w3ubf1co1vdev94g3f
  foreign key (user_id) references users;